app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000

client:
  stackoverflow:
    base-url:
  github:
    base-url:
  bot:
    base-url:

springdoc:
  swagger-ui:
    path: /swagger-ui



spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
